name: CI-CD

on:
  push:
    branches: [ main, prod ]
  workflow_dispatch:

env:
  AWS_PROFILE: "baseline-webpage"
  AWS_REGION: "ap-southeast-2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Node 18 is LTS — you can change if needed

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup NPM
        run: ./scripts/setup-npm.sh

      - name: Setup AWS (custom script)
        run: ./scripts/setup-aws.sh

      - name: Install Packages
        run: npm install

      - name: Build App
        run: npm run build

      - name: Deploy App
        run: ./scripts/deploy.sh
